<h1>Clientes</h1>
<br />

<p>
    <a href="<?php echo $this->url('livraria-admin',array('controller'=>'clientes','action'=>'new')); ?>">Novo Cliente</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Razao Social</th>
        <th>Fantasia</th>
        <th>CNPJ</th>
        <th>IE</th>
        <th>Endereco</th>
        <th>Bairro</th>
        <th>Cidade</th>
        <th>Telefone</th>
        <th>Email</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
    <tr>
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getRazao_social(); ?></td>
        <td><?php echo $entity->getFantasia(); ?></td>
        <td><?php echo $entity->getCnpj(); ?></td>
        <td><?php echo $entity->getIe(); ?></td>
        <td><?php echo $entity->getEndereco(); ?></td>
        <td><?php echo $entity->getBairro(); ?></td>
        <td><?php echo $entity->getCidade(); ?></td>
        <td><?php echo $entity->getTelefone(); ?></td>
        <td><?php echo $entity->getEmail(); ?></td>
        <td>
            <a href="<?php echo $this->url('livraria-admin-interna',
                    array('controller'=>'clientes','action'=>'edit','id'=>$entity->getId())); ?>">Editar</a>
            <a href="<?php echo $this->url('livraria-admin-interna',
                    array('controller'=>'clientes','action'=>'delete','id'=>$entity->getId())); ?>">Deletar</a>
        </td>
    </tr>
    <?php endforeach; ?>
    
</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>